version: '3.8'

services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5556:5556"
    volumes:
      - ./src:/app/src
      - ./test-results:/app/public/test-results
    command: npm run dev -- --host

  healthchecker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-checker
    volumes:
      - ./test-results:/app/public/test-results
      - ./playwright:/app/playwright 
    depends_on:
      - frontend-app