export const pacienteData = {
  Pacientes: [
    {
      depaCodigo: 99,
      depaCodigoInterno: "087",
      depaDescripcion: "Pilar",
      locaCodigo: 59,
      locaCodigoInterno: "001",
      locaDescripcion: "PILAR",
      paciCodigo: 12,
      paciCodigoInterno: "73654372",
      paciHistoriaClinica: "609066",
      paisCodigo: 1,
      paisDescripcion: "ARGENTINA",
      persAltura: "1571",
      persApellido: "DURAN SALAZAR",
      persCalle: "LAS CAMPANILLAS",
      persCodigoPadron: "0",
      persFechaAlta: "2021-10-21T11:38:12",
      persFechaNacimiento: "1981-04-04T00:00:00",
      persFechaFallecimiento: "1900-01-01T00:00:00",
      persFoto: "",
      persMail: "marcialduran@gmail.com",
      persNombre: "MARCIAL JOSE",
      persNroDocumento: "95652495",
      persOrigenAlta: "Sistema",
      persSexo: "M",
      provCodigo: 2,
      provCodigoInterno: "02",
      provDescripcion: "BUENOS AIRES",
      tdocCodigo: 1,
      tdocCodigoInterno: "1",
      tdocCodigoAfip: 96,
      tdocDescripcion: "DNI",
      Categorias: [],
      Coberturas: [
        {
          cobeCodigo: 91080,
          cobeCodigoInterno: "1",
          cobeDescripcion: "PRIVADO",
          cobeCUIT: "30-11111111-8",
          planCodigo: 43,
          planCodigoInterno: "PRI01",
          planDescripcion: "PRIVADO",
          tconCodigo: 3,
          cobeDiasVtoOrden: 90,
          pacoVigente: true,
        },
        {
          cobeCodigo: 123942,
          cobeCodigoInterno: "6",
          cobeDescripcion: "SWISS MEDICAL S.A.",
          cobeCUIT: "30-65485516-8",
          planCodigo: 2095,
          planCodigoInterno: "GLOBAL",
          planDescripcion: "GLOBAL",
          tconCodigo: 2,
          cobeDiasVtoOrden: 90,
          pacoVigente: true,
        },
        {
          cobeCodigo: 91079,
          cobeCodigoInterno: "18",
          cobeDescripcion: "OSDE",
          cobeCUIT: "30-54674125-3",
          planCodigo: 26,
          planCodigoInterno: "210",
          planDescripcion: "PLAN 210",
          tconCodigo: 1,
          pacoAfiliado: "1",
          cobeDiasVtoOrden: 90,
          pacoVigente: true,
        },
      ],
      Vinculos: [
        {
          persCodigo: 127243,
          persApellido: "AMARENA",
          persNombre: "FRANCO",
          persSexo: "M",
          tdocDescripcion: "DNI",
          persNroDocumento: "41354340",
          persFechaNacimiento: "1998-07-19T00:00:00",
          aCargo: 1,
          bajoSuCargo: 0,
          vipaCodigo: 2,
          vipaDescripcion: "Padre",
          vipaCodigoInterno: "CDED62E2-A6E2-41DB-A39D-4DBFCEE03152",
        },
        {
          persCodigo: 127858,
          persApellido: "FLORES",
          persNombre: "JIMENA IANINA",
          persSexo: "F",
          paciHistoriaClinica: "875506",
          tdocDescripcion: "DNI",
          persNroDocumento: "38152565",
          persFechaNacimiento: "1994-03-24T00:00:00",
          aCargo: 1,
          bajoSuCargo: 0,
          vipaCodigo: 1,
          vipaDescripcion: "Madre",
          vipaCodigoInterno: "1D00B322-EC5A-40C3-80D0-A170E344FEAB",
          paciCodigoInterno: "73947631",
        },
      ],
    },
  ],
};
